[package]
name = "todomd"
version = "0.1.0"
edition = "2024"

[dependencies]
pulldown-cmark = "0.13"
itertools = "0.14"
#serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand = "0.9"
rand_chacha = "0.9"
